const placeholderTabs = [
  {
    id: 0,
    index: 0,
    windowId: 0,
    url: 'https://walker.org',
    title: 'synthesize Rubber',
    mutedInfo: {},
    pinned: true,
  },
  {
    id: 1,
    index: 1,
    windowId: 1,
    url: 'https://easton.net',
    title: 'haptic Marketing Louisiana',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 2,
    index: 2,
    windowId: 2,
    url: 'https://carolanne.net',
    title: 'Seamless',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 3,
    index: 3,
    windowId: 3,
    url: 'http://nola.biz',
    title: 'Saint Helena Pound reboot Auto Loan Account',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 4,
    index: 4,
    windowId: 4,
    url: 'http://sister.biz',
    title: 'Music Programmable',
    audible: true,
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 5,
    index: 5,
    windowId: 5,
    url: 'https://merl.name',
    title: 'facilitate',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 6,
    index: 6,
    windowId: 6,
    url: 'https://hank.name',
    title: 'Trinidad and Tobago Dollar Course',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 7,
    index: 7,
    windowId: 7,
    url: 'https://zaria.net',
    title: 'Sports index Global',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 8,
    index: 8,
    windowId: 8,
    url: 'https://lenora.name',
    title: 'Associate',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 9,
    index: 9,
    windowId: 9,
    url: 'https://britney.org',
    title: 'Dynamic experiences Bedfordshire',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 10,
    index: 10,
    windowId: 10,
    url: 'http://jedediah.com',
    title: 'Wisconsin lavender',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 11,
    index: 11,
    windowId: 11,
    url: 'https://octavia.com',
    title: 'payment',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 12,
    index: 12,
    windowId: 12,
    url: 'https://chase.name',
    title: 'RAM Architect Table',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 13,
    index: 13,
    windowId: 13,
    url: 'https://hilario.net',
    title: 'bluetooth',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 14,
    index: 14,
    windowId: 14,
    url: 'https://marcelino.biz',
    title: 'systematic',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 15,
    index: 15,
    windowId: 15,
    url: 'http://jaylon.name',
    title: 'National whiteboard Florida',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 16,
    index: 16,
    windowId: 16,
    url: 'http://kellie.name',
    title: 'Kids Berkshire',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 17,
    index: 17,
    windowId: 17,
    url: 'http://elyssa.info',
    title: 'French Guiana',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 18,
    index: 18,
    windowId: 18,
    url: 'http://maribel.com',
    title: 'capability',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 19,
    index: 19,
    windowId: 19,
    url: 'http://ena.net',
    title: 'Auto Loan Account Walks Practical Metal Computer',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 20,
    index: 20,
    windowId: 20,
    url: 'http://johnathon.biz',
    title: 'Manager mint green Outdoors',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 21,
    index: 21,
    windowId: 21,
    url: 'https://johnathon.biz',
    title: 'black Lane Operative',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 22,
    index: 22,
    windowId: 22,
    url: 'http://cicero.name',
    title: 'Borders content musical',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 23,
    index: 23,
    windowId: 23,
    url: 'http://mallie.net',
    title: 'withdrawal',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 24,
    index: 24,
    windowId: 24,
    url: 'http://janessa.net',
    title: 'Auto Loan Account',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 25,
    index: 25,
    windowId: 25,
    url: 'http://tyree.info',
    title: 'Books invoice',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 26,
    index: 26,
    windowId: 26,
    url: 'https://mallie.net',
    title: 'Sausages',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 27,
    index: 27,
    windowId: 27,
    url: 'http://agustin.music',
    title: 'SMTP',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 28,
    index: 28,
    windowId: 28,
    url: 'http://webster.info',
    title: 'Equatorial Guinea Zimbabwe Dollar',
    mutedInfo: {},
    pinned: false,
  },
  {
    id: 29,
    index: 29,
    windowId: 29,
    url: 'https://andres.biz',
    title: 'ubiquitous programming solid state',
    mutedInfo: {},
    pinned: false,
  },
]

export default placeholderTabs
